### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sjcotto** [alexcg1/jina-multimodal-fashion-search#11]
Hi, so the demo website is not working and also starting the docker-compose is not working, different erros

website: 

![image](https://user-images.githubusercontent.com/3880470/170151001-d54a7b5d-0f11-491c-b894-fe2849df6f11.png)

docker-compose

![image](https://user-images.githubusercontent.com/3880470/170151016-d820f8b2-8500-4f50-972a-f207645ae052.png)

any help?

**Comment by alexcg1** [comment]
Sorry for the late reply - GitHub didn't think to notify me!

This is a weird issue - I'll take some time to look into it. I thought it might've been a case of database corruption on my own server when I saw it today, but if you're seeing it to then there's something odd afoot

I'll likely refactor my code to work on [JCloud](https://github.com/jina-ai/jcloud) anyway, since this might take some time to fix

**Comment by sjcotto** [comment]
hi , any news about running this? quick question, the CLIP only applies to the image and not the other fields or how is it?

**Comment by alexcg1** [comment]
While indexing, CLIP generates embeddings from only the image

While querying, CLIP generates embeddings either from text query or uploaded image

**Comment by alexcg1** [comment]
I just fixed this bug. Can you try running it again?

**Comment by alexcg1** [comment]
@sjcotto I'm closing this issue. Please feel free to re-open if you still see the issue
